providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs", "python3", "gcc"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install -r requirements.txt",
]

[phases.build]
cmds = ["npm run build"]
